import sys
import os

# Set working directory to the folder containing app.py
script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(script_dir)
os.chdir(script_dir)

import streamlit as st
import time
import random
import os
import pandas as pd
from datetime import datetime
 ... PROFILE_METADATA definition ...

# -----------------------------------------------------------------------------
# PASTE IT HERE (Before the login interface logic)
# -----------------------------------------------------------------------------
def get_assigned_profile(participant_id):
    """
    Searches for the participant's assigned profile in participant_profiles.csv.
    Includes a direct fallback for demo recordings.
    """
    clean_id = str(participant_id).strip().upper()
    
    # Direct bypass for video demo recording
    if clean_id == "DEMO01":
        return 1  # Launches Profile 1 (Adaptive Logic Task)
    
    profiles_csv = "participant_profiles.csv"
    if os.path.exists(profiles_csv):
        df = pd.read_csv(profiles_csv)
        match = df[df["Participant_ID"].astype(str).str.strip().str.upper() == clean_id]
        if not match.empty:
            return int(match.iloc[0]["Profile_Key"])
            
    return None

# Import profile metadata from profile_classifier.py
try:
    from profile_classifier import PROFILE_METADATA
except ImportError:
    PROFILE_METADATA = {
        1: {"profile": "Profile 1: Consistent Performer", "remedy": "Adaptive High-Load Logic Task"},
        2: {"profile": "Profile 2: Easily Distracted", "remedy": "Distractor-Inhibited Working Memory Task"},
        3: {"profile": "Profile 3: Slow Recovery / Fatigued", "remedy": "Forced Reset Attention Switching Task"},
        4: {"profile": "Profile 4: Attention Vulnerable", "remedy": "Micro-Chunked Memory Task with Cognitive Offloading"},
        0: {"profile": "Control Group", "remedy": "Standard Unguided Focus Reading"}
    }

# Streamlit Configuration
st.set_page_config(page_title="Cognitive Intervention Study", layout="wide")

# Helper Function: Read Assigned Profile Generated by profile_classifier.py
def get_assigned_profile(participant_id):
    """
    Searches for the participant's assigned profile in the CSV output
    generated by profile_classifier.py.
    """
    profiles_csv = "participant_profiles.csv"
    
    if os.path.exists(profiles_csv):
        df = pd.read_csv(profiles_csv)
        # Search for matching Participant ID (handling string/number formatting)
        match = df[df["Participant_ID"].astype(str).str.strip().str.upper() == str(participant_id).strip().upper()]
        
        if not match.empty:
            # Returns profile integer (0, 1, 2, 3, or 4)
            return int(match.iloc[0]["Profile_Key"])
            
    return None  # Return None if baseline pre-test is not completed yet

# Helper Function: Log Daily Intervention Completion
def save_completion_log(p_id, profile_name, day, score):
    log_filename = "intervention_completion_logs.csv"
    new_entry = pd.DataFrame([{
        "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "Participant_ID": p_id,
        "Profile": profile_name,
        "Day": day,
        "Score": score,
        "Completed": True
    }])
    if not os.path.exists(log_filename):
        new_entry.to_csv(log_filename, index=False)
    else:
        new_entry.to_csv(log_filename, mode='a', header=False, index=False)

# Session State Initialization
if "authenticated" not in st.session_state:
    st.session_state.authenticated = False
if "task_running" not in st.session_state:
    st.session_state.task_running = False
if "task_start_time" not in st.session_state:
    st.session_state.task_start_time = None
if "score" not in st.session_state:
    st.session_state.score = 0

# App Interface
st.title("🧠 At-Home Personalized Cognitive Intervention Platform")

# -----------------------------------------------------------------------------
# STEP 1: PARTICIPANT LOGIN & PROFILE VERIFICATION
# -----------------------------------------------------------------------------
if not st.session_state.authenticated:
    st.subheader("Participant Access Portal")
    col1, col2 = st.columns(2)
    
    with col1:
        p_id_input = st.text_input("Enter Participant ID (e.g., P001, 101):").strip()
    with col2:
        study_day = st.selectbox("Select Current Session Day:", ["Day 1", "Day 2", "Day 3", "Day 4"])

    if st.button("Access Session"):
        if p_id_input:
            # Query the CSV generated by profile_classifier.py
            assigned_profile = get_assigned_profile(p_id_input)
            
            if assigned_profile is not None:
                st.session_state.participant_id = p_id_input
                st.session_state.selected_day = study_day
                st.session_state.profile_key = assigned_profile
                st.session_state.authenticated = True
                st.rerun()
            else:
                st.error(f"Participant ID '{p_id_input}' not found in baseline pre-test records (`participant_profiles.csv`). Please complete the baseline pre-test first.")
        else:
            st.error("Please enter a valid Participant ID.")

# -----------------------------------------------------------------------------
# STEP 2: DASHBOARD & INTERVENTION RUNNER
# -----------------------------------------------------------------------------
else:
    p_id = st.session_state.participant_id
    day = st.session_state.selected_day
    p_key = st.session_state.profile_key
    user_profile = PROFILE_METADATA.get(p_key, PROFILE_METADATA[0])

    # Sidebar Information
    st.sidebar.markdown("### Participant Info")
    st.sidebar.write(f"**Participant ID:** `{p_id}`")
    st.sidebar.write(f"**Session Day:** `{day}`")
    st.sidebar.write(f"**Assigned Profile:** {user_profile['profile']}")
    st.sidebar.write(f"**Target Remedy:** {user_profile['remedy']}")
    st.sidebar.divider()
    
    if st.sidebar.button("Logout"):
        st.session_state.authenticated = False
        st.session_state.task_running = False
        st.rerun()

    st.subheader(f"Welcome, Participant {p_id} — {day}")

    if not st.session_state.task_running:
        st.info(f"**Today's Intervention:** {user_profile['remedy']}\n\nPress the button below when you are ready to begin your **10-minute session**.")
        
        if st.button("🚀 Start 10-Minute Intervention Task"):
            st.session_state.task_running = True
            st.session_state.task_start_time = time.time()
            st.session_state.score = 0
            st.rerun()

    else:
        # 10-Minute Timer (600 seconds)
        TOTAL_DURATION = 600
        elapsed_seconds = int(time.time() - st.session_state.task_start_time)
        remaining_seconds = max(0, TOTAL_DURATION - elapsed_seconds)

        progress_val = min(1.0, elapsed_seconds / TOTAL_DURATION)
        st.progress(progress_val)
        
        mins, secs = divmod(remaining_seconds, 60)
        st.metric(label="Time Remaining", value=f"{mins:02d}:{secs:02d}")

        if elapsed_seconds >= TOTAL_DURATION:
            st.balloons()
            st.success(f"🎉 **Session Complete!** You have finished {day}.")
            save_completion_log(p_id, user_profile['profile'], day, st.session_state.score)
            
            if st.button("Exit Session"):
                st.session_state.authenticated = False
                st.session_state.task_running = False
                st.rerun()
            st.stop()

        st.divider()

        # PROFILE 1: Adaptive High-Load Logic Task
        if p_key == 1:
            st.markdown("### Adaptive Logic Task")
            n1, n2 = random.randint(12, 89), random.randint(12, 89)
            col_a, col_b = st.columns(2)
            col_a.markdown(f"#### Solve Puzzle: `{n1} + {n2} = ?`")
            u_ans = col_b.number_input("Your Answer:", step=1, key=f"p1_{elapsed_seconds}")
            
            if st.button("Submit Answer", key=f"btn_p1_{elapsed_seconds}"):
                if u_ans == (n1 + n2):
                    st.session_state.score += 10
                    st.success("Correct!")
                st.rerun()

        # PROFILE 2: Distractor-Inhibited Working Memory Task
        elif p_key == 2:
            st.markdown("### Working Memory Task (Auditory Interference Active)")
            if os.path.exists("cafeteria_noise.wav"):
                st.audio("cafeteria_noise.wav", format="audio/wav", autoplay=True, loop=True)
            
            st.info("Memorize Sequence: **4 — 8 — 2 — 9 — 1 — 7**")
            recall_input = st.text_input("Enter sequence digits in order:", key=f"p2_{elapsed_seconds}")
            
            if st.button("Submit Recall", key=f"btn_p2_{elapsed_seconds}"):
                st.session_state.score += 10
                st.success("Response recorded!")
                st.rerun()

        # PROFILE 3: Forced Reset Attention Switching Task
        elif p_key == 3:
            st.markdown("### Target Tracking Task")
            cycle_phase = elapsed_seconds % 120
            if cycle_phase >= 90:
                st.warning("🧘 **FORCED RESET INTERVAL:** Follow the Breathing Pacer Circle")
                st.markdown("#### Inhale (4s) ... Hold (4s) ... Exhale (4s)")
                st.progress((cycle_phase - 90) / 30.0)
            else:
                if st.button("🎯 TARGET ACTIVE — CLICK NOW", key=f"btn_p3_{elapsed_seconds}"):
                    st.session_state.score += 5
                    st.success("Target Captured!")

        # PROFILE 4: Micro-Chunked Memory Task with Cognitive Offloading
        elif p_key == 4:
            st.markdown("### Micro-Chunked Task Workspace")
            col_left, col_right = st.columns([2, 1])
            with col_left:
                st.info("Task Sequence: Calculate tax for Item A ($240), Item B ($130), Item C ($510).")
            with col_right:
                st.text_area("Digital Scratchpad:", height=200, key="scratchpad")

        # CONTROL GROUP
        else:
            st.markdown("### Standard Focus Reading Exercise")
            st.text_area("Static Material", 
                         value="Cognitive psychology is the scientific study of mental processes such as attention, language use, memory, perception...", 
                         height=250, disabled=True)
